Chat/Models/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Chat.Models
{
    public class Message
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Text { get; set; }
        public DateTime sendTime { get; set; }
    }
}

Chat/Models/MessageDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Chat.Models
{
    public class MessageDetail
    {
        public string UserName { get; set; }

        public string Message { get; set; }
    }
}

Chat/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Chat.Models
{
    public class User
    {
        public int ID { get; set; }
        [Key]
        public string Login { get; set; }
        public string Password { get; set; }
    }
}

Chat/Models/UserDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Chat.Models
{
    public class UserDetail
    {
        public string ConnectionId { get; set; }
        public string UserName { get; set; }
    }
}

Chat/Controllers/ChatController.cs
using Chat.Domain;
using Chat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.Controllers
{
    public class ChatController : Controller
    {

        ChatDBContext dbcontext = new ChatDBContext();
        // GET: Chat
        public ActionResult Chat()
        {
            return View();
        }

        public JsonResult GetHistory(string name="", string dtfrom="", string dtto="")
        {
            IQueryable<Message> messageslist;
            
            messageslist = dbcontext.Messages;
            DateTime dtf;
            DateTime dtt;

            if (DateTime.TryParse(dtfrom, out dtf))
            {
                messageslist = messageslist.Where(x => x.sendTime >= dtf);
            }
            if (DateTime.TryParse(dtto, out dtt))
            {
                messageslist = messageslist.Where(x => x.sendTime <= dtt);
            }

            if (!string.IsNullOrEmpty(name))
            {
                messageslist = messageslist.Where(x => x.UserName == name);
            }

            var messages = messageslist.ToList().Select(s => new
            {
                sendTime = s.sendTime.ToString("dd/MM/yyyy HH:mm:ss"),
                Text = s.Text,
                UserName = s.UserName
            });
            return Json(messages, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            dbcontext.Dispose();
            base.Dispose(disposing);
        }
    }
}

Chat/Views/Chat/Chat.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Chat</title>
    <link type="text/css" rel="stylesheet" href="~/Css/bootstrap.css" />
    <link type="text/css" rel="stylesheet" href="~/Css/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" href="~/Css/bootstrap-datetimepicker.min.css" />
    <link type="text/css" rel="stylesheet" href="/Css/Style.css" />
  
    <script src="/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>  
    <script src="~/Scripts/moment-with-locales.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>

    <script src="/Scripts/jquery.signalR-2.2.2.js"></script>
    
    <script src="/signalr/hubs"></script>

    <script src="~/Scripts/app.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My chat", "Chat", "Chat", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a id="btnLogin">Вход</a></li>
                    <li><a id="btnRegistration">Регистрация</a></li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        
        <div class="row">
            <!-- Login section-->
            <div id="loginSection" class="col-md-8">
                <div class="form-horizontal">
                    <h4>Введите данные для входа</h4>
                    <hr />
                    <div class="form-group">
                        <label class="col-md-2 control-label">Логин</label>
                        <div class="col-md-10">
                            <input type="text" id="inputLogin" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label">Пароль</label>
                        <div class="col-md-10">
                            <input type="text" id="inputPswd" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Войти" id="btnStartChat" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
            <!--End login section-->
            <!--Registration section-->
            <div id="regSection" class="col-md-8">
                <div class="form-horizontal">
                    <h4>Введите данные для регистрации</h4>
                    <hr />
                    <div class="form-group">
                        <label class="col-md-2 control-label">Логин</label>
                        <div class="col-md-10">
                            <input type="text" id="inputRegLogin" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label">Пароль</label>
                        <div class="col-md-10">
                            <input type="text" id="inputRegPswd" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Регистрация" id="btnRegisterChat" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
            <!--End registration section-->
        </div>
        <div class="row">
            <div id="divChat" class="panel panel-default">
                <div class="panel-heading">
                    Добро пожаловать [<span id='spanUser'></span>]

                </div>
                <div class="panel-body">
                    <div id="divChatWindow" class="chatWindow">
                    </div>
                    <div id="divusers" class="users">
                    </div>
                </div>
                <div class="panel-footer">
                    <input class="textbox" type="text" id="txtMessage" />
                    <button id="btnSendMsg" type="button" class="btn btn-info">Отправить</button>
                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#historyModal">Посмотреть историю</button>
                </div>
            </div>
            <input id="hdId" type="hidden" />
            <input id="hdUserName" type="hidden" />
            
            <div id="historyModal" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">История чата</h4>
                            <div class="form-horizontal">
                                <div class="form-group">
                                    <label class="col-sm-1">c</label>
                                    <input class="col-md-4" type="text" id="dateFrom" />
                                <div class="form-group">
                                    <label class="col-sm-1">по</label>
                                    <input class="col-md-4" type="text" id="dateTo" />
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-1">Имя</label>
                                    <input class="col-ms-offset-3" type="text" id="inputName" />
                                    <button id="btnGetHistory" class="btn btn-default col-sm-offset-4"> Показать</button>
                                </div>
                            </div>
                        </div>
                        <div class="modal-body" id="chatHistory" style="float: left; width: 100%; height: 200px;overflow-y: scroll;">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <hr />
        <footer>
            <p>&copy; 2018 Akyl Zholonov</p>
        </footer>
    </div>
</body>
</html>